CVBuilder/CVApp/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', views.Login, name='login'),
    path('register/', views.Register, name='register'),

    path('', views.Home, name='home'),
    path('logout/', views.Logout, name="logout"),
    path('dashboard/', views.Dashboard, name="dashboard"),
    path('ChangePassword', views.ChangePassword, name="ChangePassword"),
    # path('index/', views.Index, name='index'),
    path('resume/', views.Resume, name='resume'),
    path('contact/', views.Contact, name='contact'),
    path('about/', views.About, name='about'),
    path('filter/', views.search, name='filter'),
    path('filterdone/', views.FilterDone, name='filterdone'),

    path('PersonalInfo/', views.PersonalInfo, name="PersonalInfo"),
    path('PersonalInfo1/', views.PersonalInfo1, name="PersonalInfo1"),
    path('PersonalInfo2/', views.PersonalInfo2, name="PersonalInfo2"),
    path('PersonalInfo3/', views.PersonalInfo3, name="PersonalInfo3"),
    path('PersonalInfo4/', views.PersonalInfo4, name="PersonalInfo4"),
    path('PersonalInfo5/', views.PersonalInfo5, name="PersonalInfo5"),
    path('PersonalInfo6/', views.PersonalInfo6, name="PersonalInfo6"),
    path('PersonalInfo7/', views.PersonalInfo7, name="PersonalInfo7"),
    path('mail/', views.sendmail, name='mail'),

    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='reset/password_reset.html',
             subject_template_name='reset/password_reset_subject.txt',
             email_template_name='reset/password_reset_email.html',
             success_url='done'
         ),name='password_reset'),

    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='reset/password_reset_done.html'
         ),name='password_reset_done'),

    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='reset/password_reset_confirm.html'
         ),name='password_reset_confirm'),

    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='reset/password_reset_complete.html'
         ),name='password_reset_complete'),

]

CVBuilder/CVBuilder/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("CVApp.urls")),






              ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

CVBuilder/CVApp/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from multiselectfield import MultiSelectField
# MY_CHOICES = (('item_key1', 'Item title 1.1'),
#               ('item_key2', 'Item title 1.2'),
#               ('item_key3', 'Item title 1.3'),
#               ('item_key4', 'Item title 1.4'),
#               ('item_key5', 'Item title 1.5'))

def get_upload_path(instance,filename):
    return 'document/{0}/{1}'.format(instance.user.username,filename)
# Create your models here.

class Resume(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    picture = models.FileField(upload_to = get_upload_path,blank=True)
    first_name = models.CharField(max_length=50, default='')
    middle_name = models.CharField(max_length=50, default='')
    last_name = models.CharField(max_length=50, default='')
    gender = models.CharField(max_length=10)
    birth_date = models.CharField(max_length=20,default='1999-12-31')

    email = models.EmailField(default='none@email.com')
    Address = models.CharField(max_length=100, default='')
    city = models.CharField(max_length=255, default='')
    state = models.CharField(max_length=255, default='')
    Postal_Zip_Code = models.IntegerField(default='123')
    Phone_Number = models.IntegerField(default='123')


#Qualifications:
    ssc_school=models.CharField(max_length=100, default='')
    ssc_year_of_passing=models.IntegerField( default='0')
    ssc_percentage=models.FloatField(default='100')

    hsc_school=models.CharField(max_length=100, default='')
    hsc_year_of_passing=models.IntegerField( default='0')
    hsc_percentage=models.FloatField(default='100')


    #UG
    ug_college=models.CharField(max_length=100, default='')
    ug_collage_cgpa=models.FloatField(default='100')
    ug_degree=models.CharField(max_length=100, default='')

    #PG
    pg_college = models.CharField(max_length=100, default='')
    pg_collage_cgpa = models.FloatField(default='100')
    pg_degree=models.CharField(max_length=100, default='')


    # skills = MultiSelectField(choices=MY_CHOICES)
    skills=models.CharField(max_length=100)
    any_other_qualification=models.CharField(max_length=200,default='')
    internship_experience = models.CharField(max_length=200, default='')

    certificates = models.FileField(upload_to=get_upload_path,default = 'no-img.jpg', blank=True)

    about_you = models.FileField(upload_to=get_upload_path, blank=True)

    Github=models.URLField(max_length=200, default='')
    linkedin=models.URLField(max_length=200, default='')
    facebook=models.URLField(max_length=200, default='')


    def __str__(self):
        return self.user.username




def create_resume(sender, **kwargs):
    if kwargs['created']:
        profile = Resume.objects.create(user=kwargs['instance'])

post_save.connect(create_resume, sender=User)


class ContactUs(models.Model):
    username=models.CharField(max_length=100, default="")
    From=models.EmailField(max_length=100, default="")
    Subject=models.CharField(max_length=100, default="")
    Message=models.CharField(max_length=1000, default="")


    def __str__(self):
        return self.username


class Company(models.Model):
    company_name=models.CharField(max_length=500, default="")
    location=models.CharField(max_length=500, default="")
    job_title=models.CharField(max_length=100, default="")


    def __str__(self):
        return self.company_name

CVBuilder/CVApp/forms.py
from . import models
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import (formset_factory, modelformset_factory)
from django.forms import ClearableFileInput
from django_select2.forms import Select2MultipleWidget

class CreateUserForm(UserCreationForm):
    class Meta:
        model=User
        fields = ['username', 'email', 'first_name','last_name','password1', 'password2']


class PersonalInfo(forms.ModelForm):
    birth_date=forms.CharField()
    picture = forms.FileField(widget=forms.FileInput)
    class Meta:
        model=models.Resume
        fields=['picture','first_name','middle_name','last_name','gender','birth_date',

                # 'email','Address','city','state','Postal_Zip_Code','Phone_Number',
                #
                # 'ssc_school','ssc_board','ssc_year_of_passing','ssc_percentage', 'hsc_school','hsc_board','hsc_year_of_passing','hsc_percentage',
                #
                # 'ug_college','ug_university','ug_collage_cgpa','ug_degree','pg_college','pg_university','pg_collage_cgpa','pg_degree',
                #
                # 'skills','any_other_qualification','internship_experience',
                #
                # 'certificates','about_you'

                ]




class PersonalInfo1(forms.ModelForm):
    class Meta:
        model=models.Resume
        fields=['email','Address','city','state','Postal_Zip_Code','Phone_Number']


class PersonalInfo2(forms.ModelForm):
    class Meta:
        ssc_year_of_passing=forms.IntegerField()
        model=models.Resume
        fields=['ssc_school','ssc_year_of_passing','ssc_percentage', 'hsc_school','hsc_year_of_passing','hsc_percentage',]

class PersonalInfo3(forms.ModelForm):
    pg_college=forms.CharField(label='Post Graduation', required=False)
    class Meta:
        model=models.Resume
        fields=['ug_college','ug_collage_cgpa','ug_degree','pg_college','pg_collage_cgpa','pg_degree',]




class PersonalInfo4(forms.ModelForm):
    any_other_qualification=forms.CharField(label='Other Qualifications',widget=forms.Textarea() ,required=False)
    class Meta:
        model=models.Resume
        fields=['any_other_qualification',]


class PersonalInfo5(forms.ModelForm):
    about_you = forms.FileField(widget=forms.FileInput)
    internship_experience = forms.CharField( widget=forms.Textarea(), required=False)

    class Meta:
        model=models.Resume
        fields=['about_you','internship_experience']


class PersonalInfo6(forms.ModelForm):
    certificates = forms.FileField(widget=forms.FileInput)

    class Meta:
        model=models.Resume

        fields=['skills','certificates']
        widgets = {
        # 'certificates': forms.FileField(attrs={'class': 'formset-field'}),

            'certificates': ClearableFileInput(attrs={'multiple': True})
        }


class PersonalInfo7(forms.ModelForm):

    class Meta:
        model=models.Resume
        fields=['Github','linkedin','facebook']



class ContactUsForm(forms.ModelForm):
    username=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}))
    From = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control' , 'placeholder':'Your Email'}))
    Subject=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' , 'placeholder':'Subject'}))
    Message=forms.CharField(widget=forms.TextInput(attrs={'class':'form-control' , 'placeholder':'Message'}))
    class Meta:
        model=models.ContactUs
        fields=['username','From','Subject','Message']



class CompanyForm(forms.ModelForm):

    class Meta:
        model=models.Company
        fields=['company_name','job_title','location']

CVBuilder/templates/ChangePassword.html
{% extends 'base1.html' %}
{% load static %}

{% block body %}
    <footer>
        <form method="POST">
            {% csrf_token %}

            <div class="row mr-0 ml-0">

                <div class="col-md-8 content-us" >
                    <div class="contact-form" id="contact">
                        <h3 class="text-uppercase">Change Password</h3>
                            {{ passform.as_p}}<br>
                        <button type="submit">Send</button>
                    </div>
                </div>
            </div>
            </div>
    </footer>
{% endblock %}

CVBuilder/templates/Fdone.html
{% extends 'base1.html' %}
{% load static %}

{% block body %}

    <footer>
        <div class="row mr-0 ml-0" style="background: #282828;">

                <div class="contact-form" id="contact" >
                    <h3 class="text-uppercase">Invitation sent Successfully</h3>
                </div>
        </div>
    </footer>




{% endblock %}

CVBuilder/templates/about.html
{% extends 'base1.html' %}
{% load static %}

{% block body %}
<footer>

<div class="container-fluid fh5co-recent-work" style="background: #282828; padding-top: 500px">
    <div class="container contact-pop">
      <div class="row">
        <div class="col-md-6  pr-0">
          <div class="card"> <img class="card-img w-100" src="{% static 'home/assets/img/girl3.jpg' %}" alt="">
            <div class="card-img-overlay"> </div>
          </div>
        </div>
        <div class="col-md-6 pl-0" id="about">
          <div class="content">
            <h3>Name</h3>
            <h4>designation</h4>
            <hr />
            <p>ABOUT 
          </div>
          </div>
        </div>
      </div>
</div>
</footer>
{% endblock %}

CVBuilder/templates/base1.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="colorlib.com">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up Form</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="{% static 'home/assets/css/style.css'%}">



    {% block head %}{% endblock %}
    <style>
        a {
            color: #e90e65;
        }
        a:hover {
            color: #f3e7e8;
        }
        .panel-group .active .panel-heading h1 a {
            color: #e90e65;
        }
        body{
            background: #282828;
            font-size: 15px;
        }
        input{
            font-size: 15px;
        }

        .scrollable-menu {
            height: auto;
            max-height: 200px;
            overflow-x: hidden;
        }

        /* unvisited link */
        a:link {
            color: #f3e7e8;
        }



        /* selected link */
        a:active {
            color: #f3e7e8;
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-md  fixed-top maine-menu" style="background-color: black;" >
    <div class="container" style="background-color: black;">
        <button class="navbar-toggler ml-auto" data-target="#my-nav" onclick="myFunction(this)" data-toggle="collapse"> <span class="bar1"></span> <span class="bar2"></span> <span class="bar3"></span> </button>
        <div id="my-nav" class="collapse navbar-collapse">
            <ul class="navbar-nav mx-auto">
                {% if user.username %}
                    <li class="nav-item "> <a class="nav-link active" href="{% url 'dashboard' %}">Home</a> </li>
                {% elif not user.username %}
                    <li class="nav-item "> <a class="nav-link active" href="{% url 'home' %}">Home</a> </li>
                {% endif %}


                <li class="nav-item"> <a class="nav-link" href="{% url 'about' %}" tabindex="-1" aria-disabled="true" >About</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'PersonalInfo' %}" tabindex="-1" aria-disabled="true">Create Resume</a></li>


                {% if user.username %}
                    <li class="nav-item"> <a class="nav-link" href="{% url 'ChangePassword' %}" tabindex="-1" aria-disabled="true">Change Password</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'logout' %}" tabindex="-1" aria-disabled="true">Logout</a></li>
                {% elif not user.username %}
                    <li class="nav-item"> <a class="nav-link" href="{% url 'login' %}" tabindex="-1" aria-disabled="true">Login</a></li>
                {% endif %}


                {% if not user.username %}
                    <li class="nav-item"> <a class="nav-link" href="{% url 'register' %}" tabindex="-1" aria-disabled="true">Register</a></li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'filter' %}" tabindex="-1" aria-disabled="true">Search</a></li>
                {% endif %}


                <li class="nav-item"> <a class="nav-link" href="{% url 'contact' %}" tabindex="-1" aria-disabled="true">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>




{% block body %}{% endblock %}


<script src="{% static 'home/assets/js/jquery-3.3.1.slim.min.js'%}"></script>
<script src="{% static 'home/assets/js/popper.min.js'%}" ></script>
<script src="{% static 'home/assets/js/bootstrap.min.js'%}"></script>
<script src="{% static 'home/assets/js/owl.carousel.min.js'%}"></script>
<script src="{% static 'home/assets/js/main.js'%}"></script>
<script src="{% static 'register/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'register/js/main.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
{% block script %}{% endblock %}
</body>
</html>

CVBuilder/templates/contact.html
{% extends 'base1.html' %}
{% load static %}

{% block body %}

    <footer>
        <div class="row mr-0 ml-0">
            <div class="col-md-6 content-us" style="background: #282828;">
                <div class="contact-form" id="contact">
                    <h3 class="text-uppercase">Contact me</h3>
                    <form method="post">
                        {% csrf_token %}
                        {% if user.username %}
                            <input type="text" name="username" class="form-control" placeholder="Username" required="" value="{{user.username}}" id="id_username">
                            <input type="email" name="From" class="form-control" placeholder="Your Email" required="" value="{{user.email}}"id="id_From">
                        {% else %}
                            {{ Cform.username }}
                            <input type="email" name="From" class="form-control" placeholder="Your Email" required="" value="{{user.email}}"id="id_From">
                        {% endif %}

                        {{ Cform.Subject }}
                        {{ Cform.Message }}

                        <button type="submit" value="send" onclick="sendEmail()" >Send</button>
                    </form>
                </div>
            </div>
        </div>



        <script src="https://smtpjs.com/v3/smtp.js"></script>

        <script type="text/javascript">
            function sendEmail() {
                var x=document.getElementById("id_From").value;

                Email.send({
                    Host: "smtp.gmail.com",
                    Username: "harshdeepmahajan@mvaburhanpur.com",
                    Password: "Deep@.com",

                    To:x,

                    From: "harshdeepmahajan@mvaburhanpur.com",
                    Subject: "mail related your query",
                    Body: "hello thank you for contacting us your problem will be solved soon",
                })
            }
        </script>
    </footer>
{% endblock %}

CVBuilder/templates/filter.html
{% extends 'base1.html' %}
{% load static %}
{% load widget_tweaks %}


{% block head %}
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Colrolib Templates">
    <meta name="author" content="colorlib.com">
    <meta name="keywords" content="Colrolib Templates">

    <!-- Title Page-->
    <title>Au Form Wizard</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- Icons font CSS-->
    <link href="{% static 'filter/vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'filter/vendor/font-awesome-4.7/css/font-awesome.min.css'%}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
    <!-- Vendor CSS-->
    <link href="{% static 'filter/vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'filter/vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">
    <!-- Main CSS-->
    <link href="{% static 'filter/css/main.css' %}" rel="stylesheet" media="all">
{% endblock %}

{% block body %}
    <div class="page-wrapper bg-color-1 p-t-395 p-b-120" style="background: #282828">
        <div class="wrapper wrapper--w1070" style="max-width: 1145px;">
            <div class="card card-7">
                <div class="card-body">
                    <form class="form" method="get">
                        <div class="input-group input--medium">
                            <label class="label">First Name</label>
                            {% render_field filter.form.first_name class="input--style-1" %}
                        </div>
                        <div class="input-group input--medium">
                            <label class="label">Gender</label>
                            {% render_field filter.form.gender class="input--style-1" %}
                        </div>
                        <div class="input-group input--medium">
                            <label class="label">City</label>
                            {% render_field filter.form.city class="input--style-1" %}
                        </div>
                        <div class="input-group input--medium">
                            <label class="label">State</label>
                            {% render_field filter.form.state class="input--style-1" %}
                        </div>
                        <div class="input-group input--medium">
                            <label class="label">Skills</label>
                            {% render_field filter.form.skills class="input--style-1" %}
                        </div>
                        <button class="btn-submit" type="submit" style="line-height: 100px;color: whitesmoke; background: #e90e65;">Filter</button>
                    </form>


                    <br><br>

                    <table class="table">
                        <thead class="thead-dark">
                        <tr>
                            <th>Full Name</th>
                            <th>First Name</th>
                            <th>Gender</th>
                            <th>City</th>
                            <th>State</th>
                            <th>Skills</th>
                            <th>Resume Video</th>
                            <th>Send Invitation Mail</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for resume in filter.qs %}
                            <tr style="color: whitesmoke;">
                            <td>
                                <img src="{{ resume.picture.url }}" height="150px" width="150px" align="right">
                                {{ resume.first_name }} {{ resume.middle_name }} {{ resume.last_name }}
                            </td>
                            <td>{{ resume.first_name }}</td>
                            <td>{{ resume.gender }}</td>
                            <td>{{resume.city }}</td>
                            <td>{{ resume.state  }}</td>
                            <td>{{ resume.skills  }}</td>
                            <td>
                                <video width="200" height="150" controls>
                                    <source src="{{ resume.about_you.url }}" type="video/mp4">
                                </video>
                            </td>
                            <form method="post">
                            {% csrf_token %}
                            <td><input type="checkbox" style="zoom: 1.7;" value="{{ resume.email }}" name="email" id="id_email" readonly " ></td>
                        {% endfor %}
                        </tbody>

                    </table>
                    <h2 style="color: whitesmoke;"> Write Detail of your company and send mail</h2><br>
                    <div class="input-group input--medium">
                        <label class="label">Company</label>
                        <input type="text" class="input--style-1"  name="company" id="id_company" >
                    </div>
                    <div class="input-group input--medium">
                        <label class="label">Location</label>
                        <input type="text" class="input--style-1"  name="location" id="id_location" >
                    </div>
                    <div class="input-group input--medium">
                        <label class="label">Job Title</label>
                        <input type="text" class="input--style-1"  name="job_title" id="id_job_title" >
                    </div>
                    <input type="submit" id="xyz" class="btn-submit" onclick="sendEmail()" value="Send Mail" style="width:45%;line-height: 100px;color: whitesmoke; background: #e90e65; padding-block: 100px;">
                    </form>
                </div>
            </div>
        </div>
    </div>


    <script>
        function getCheckedValues() {
            return Array.from(document.querySelectorAll('input[type="checkbox"]'))
                .filter((checkbox) => checkbox.checked)
                .map((checkbox) => checkbox.value);
        }

        const resultEl = document.getElementById('result');

        document.getElementById('showResult').addEventListener('click', () => {
            resultEl.innerHTML = getCheckedValues();

        });

    </script>


    <script src="https://smtpjs.com/v3/smtp.js"></script>

    <script type="text/javascript">
        function sendEmail() {
            var x = getCheckedValues();
            var a =document.getElementById("id_company").value
            var b =document.getElementById("id_location").value
            var c =document.getElementById("id_job_title").value

            for (i = 0; i < x.length; i++) {
                Email.send({
                    Host: "smtp.gmail.com",
                    Username: "harshdeepmahajan@mvaburhanpur.com",
                    Password: "Deep@.com",

                    To: x[i],

                    From: "harshdeepmahajan@mvaburhanpur.com",
                    Subject: "Invitation for job in company" + a,
                    Body: "company name: "+ a + " location:"+ b +" job title:"+ c +"helllo this is invitation for job",

                })
            }
        }
    </script>



{% endblock %}
{% block script %}
    <!-- Jquery JS-->
    <script src="{% static 'filter/vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'filter/vendor/select2/select2.min.js'%}"></script>
    <script src="{% static 'filter/vendor/jquery-validate/jquery.validate.min.js' %}"></script>
    <script src="{% static 'filter/vendor/bootstrap-wizard/bootstrap.min.js'%}"></script>
    <script src="{% static 'filter/vendor/bootstrap-wizard/jquery.bootstrap.wizard.min.js' %}"></script>
    <script src="{% static 'filter/vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'filter/vendor/datepicker/daterangepicker.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!-- Main JS-->
    <script src="{% static 'filter/js/global.js' %}"></script>


{% endblock %}

CVBuilder/templates/mail.html
{% extends 'base1.html' %}
{% load static %}

{% block body %}

    <footer>
        <div class="row mr-0 ml-0" style="background: #282828;">

                <div class="contact-form" id="contact" >
                    <h3 class="text-uppercase">Message sent Successfully, We will contact you soon!!!<br> Thank You</h3>
                </div>
        </div>
    </footer>

{% endblock %}